from __future__ import annotations

import platform
import re
from urllib.parse import urlencode

from smartswitch_core.privacy import redact_absolute_paths
from gui.version import get_app_version

ISSUE_NEW_URL = "https://github.com/sachk/smartswitch-explorer/issues/new"

_EMAIL_RE = re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.IGNORECASE)
_PACKAGE_ID_RE = re.compile(r"\b(?:[a-zA-Z][\w]*\.){2,}[a-zA-Z][\w]*\b")
_LONG_NUMBER_RE = re.compile(r"\b\d{12,}\b")
_HEX_SECRET_RE = re.compile(r"\b[0-9A-Fa-f]{32,}\b")


def anonymize_diagnostic_text(text: str) -> str:
    sanitized = _EMAIL_RE.sub("<email>", str(text))
    sanitized = _PACKAGE_ID_RE.sub("<package-id>", sanitized)
    sanitized = _LONG_NUMBER_RE.sub("<number>", sanitized)
    sanitized = _HEX_SECRET_RE.sub("<redacted-hex>", sanitized)
    return redact_absolute_paths(sanitized)


def build_anonymized_report(errors: list[object], warnings: list[object]) -> str:
    lines = [
        "SmartSwitch Explorer diagnostic report",
        f"Version: {get_app_version()}",
        f"Operating system: {platform.system() or 'Unknown'}",
        "Privacy: paths, email addresses, package IDs, long identifiers, and key-like hex values were removed.",
        "No backup files or backup metadata are included.",
    ]

    for heading, values in (("Errors", errors), ("Warnings", warnings)):
        if not values:
            continue
        lines.extend(["", f"{heading} ({len(values)}):"])
        for value in values[:20]:
            sanitized = anonymize_diagnostic_text(str(value))
            lines.append(f"- {sanitized[:1000]}")
        if len(values) > 20:
            lines.append(f"- … {len(values) - 20} more omitted")
    return "\n".join(lines)


def build_issue_url(report: str) -> str:
    report_for_url = report
    if len(report_for_url) > 6000:
        report_for_url = report_for_url[:6000] + "\n… report truncated for URL"
    body = (
        "The diagnostic report below was generated by SmartSwitch Explorer. "
        "I reviewed it before submitting.\n\n"
        f"```text\n{report_for_url}\n```\n\n"
        "What I selected for export:\n"
        "What I expected:\n"
    )
    query = urlencode(
        {
            "title": "Backup export failed",
            "body": body,
            "labels": "bug",
        }
    )
    return f"{ISSUE_NEW_URL}?{query}"
